# Generated by Django 4.2.5 on 2023-10-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='image',
            field=models.URLField(max_length=2000),
        ),
    ]
